version: "3.8"
services:
  mongodb:
    image: mongo:6.0.2
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/jack/databases/6:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
