version: "3.8"
services:
  mongodb:
    image: mongo:6.0.2
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/jack/databases/6:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  mongodb3:
    image: mongo:3.6.23
    container_name: mongodb3
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/jack/databases/3:/data/db
    ports:
      - 27013:27017
    restart: unless-stopped
  mongodb4:
    image: mongo:4.2.17
    container_name: mongodb4
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/jack/databases/4:/data/db
    ports:
      - 27014:27017
    restart: unless-stopped
